x = 6
y = 7
print(f"x = {x}")
print(f"y = {y}")
x += y
print("Operation x += y")
print(f"x = {x}")
x -= y
print("Operation x -= y")
print(f"x = {x}")
x *= y
print("Operation x *= y")
print(f"x = {x}")
x /= y
print("Operation x /= y")
print(f"x = {x}")
print("Operation x %= y")
print(f"x = {x}")
x **= y
print("Operation x **= y")
print(f"x = {x}")
print("Operation x //= y")
print(f"x = {x}")
